protected/modules/profil/controllers/MembresController.php
<?php

class MembresController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('deny',  
				'actions'=>array('update','uploadImage','requestCities'),
				'users'=>array('?'),
			),
			array('allow', 
				'actions'=>array('update','uploadImage','requestCities'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}



	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate()
	{

		$model=$this->loadModel(Yii::app()->user->getID());
		
		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Membres']))
		{
			$model->attributes=$_POST['Membres'];
			$model->objectif=$_POST['objectif'];
			$model->date_naissance=$model->annee.'-'.$model->mois.'-'.$model->jour;
			
			if($model->save())
				$this->redirect(ContactMembres::model()->getUpdateUrl());
		}

		if($model->date_naissance!=NULL){
			
			$model->annee=substr($model->date_naissance,0,4);
			$model->mois=substr($model->date_naissance,-5,2);
			$model->jour=substr($model->date_naissance,8,2);
		}
		
		//Suggest group
	 	$suggestGroups=ContactGroupes::model()->getSuggest();

		//Suggest contacts to user
		$suggestContacts=array();
 		$suggestId=array();
 		$suggestId=ContactMembres::model()->getSuggestIndex();

 		if($suggestId!=false)
 		{	
 											
		 	foreach ($suggestId as $value)
			{
				$suggestContacts[$value]=ContactMembres::model()->queryContact($value);
												
			}
		}
		
		$this->render('update',array(
										'model'=>$model,
										'suggestGroups'=>$suggestGroups,
										'suggestMembres'=>$suggestContacts
									));
	}

	public function actionUploadImage(){
		
		$dir=Yii::getPathOfAlias('application.modules.profil.assets.images');

		
		$nouveauImage=new UploadImages();
		
		if(isset($_POST['UploadImages'])){
			
			$nouveauImage->attributes=$_POST['UploadImages'];
			$this->performAjaxValidation($nouveauImage);
			
			$file=CUploadedFile::getInstance($nouveauImage,'image');
			
			
			if($nouveauImage->validate()){				
				
				$file->saveAs($dir.'/'.Yii::app()->user->getID());
				$membres=Membres::model()->findByPk(Yii::app()->user->getID());
				$membres->chemin_avatar=Yii::app()->assetManager->publish($dir.'/'.Yii::app()->user->getID());
				$membres->save();
				
				$this->redirect(ContactMembres::model()->getUpdateUrl());
			}
			
		}
		
		$this->render('uploadImage',array(
											'imageProfil'=>$nouveauImage,		
										 ));
		
	}
	
	//Pour modifier un membre
	public function loadModel($id)
	{
		$model=Membres::model()->findByPk($id);
		
		if($model===null)
			throw new CHttpException(404,'La page demandée n\'existe pas.');
			
			
		return $model;
	}

	//Pour ajouter les villes dans le formulaire
	public function actionRequestCities()
	{
		
		if(isset($_POST['Membres']['pays']))
		{
			$data=Villes::model()->findAll('b_pays_id=:parent_id',array(':parent_id'=>(int)$_POST['Membres']['pays']));

       		$data=CHtml::listData($data,'id','ville');
		
		
			foreach($data as $key=>$value)
				 echo CHtml::tag('option', array('value'=>$key), CHtml::encode($value), true);
		}
	}
	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='membres-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/profil/controllers/MessagesController.php
<?php

class MessagesController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('deny', 
				'actions'=>array('received','sent','compose','delete','read','composeProfile','autocomplete','reply'),
			
				'users'=>array('?'),
			),
			array('allow', 
				'actions'=>array('received','sent','compose','delete','read','composeProfile','autocomplete','reply'),
			
				'users'=>array('@'),
			),
			
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}


	//Nouveau message
	public function actionCompose()
	{
		$model=new Messages;

		// Uncomment the following line if AJAX validation is needed
		$this->performAjaxValidation($model);

		if(isset($_POST['Messages']))
		{  	
				$model->attributes=$_POST['Messages'];
				$model->date_envoie=Date('Y-m-d H:i:s');
				$model->expediteur_id=Yii::app()->user->getID();
				$model->destinataire_id=$_POST['destinataire_id'];
				
			if($model->save())
			{
				$expediteur=Membres::model()->getViewIdInfo(Yii::app()->user->getID());
				$destinataire=Membres::model()->getViewIdInfo($_POST['destinataire_id']);
	
				//Send an email to notify $destinataire
				$mail= new YiiMailMessage;
				$mail->view='message';
				$mail->setBody(array('nom'=>$expediteur['nom'],'prenom'=>$expediteur['prenom'],'id'=>$expediteur['id']),'text/html');
				$mail->addTo($destinataire['email']);
				$mail->from=$expediteur['email'];
				$mail->subject=$model->objet;
				Yii::app()->mail->send($mail);
				
				Yii::app()->user->setFlash('messageSent',"Message envoyé" );
				$this->redirect(Messages::model()->getReceivedUrl());
			}
			
		}
			//Inbox
			$demandesContacts=ContactMembres::model()->getDemandesCount();
			$nouveauMessages=Messages::model()->getNewMessagesCount();
			$recommandationRequest=Recommandations::model()->getRecommandationRequestCount();
		
			$this->render('compose',array(
											 'model'=>$model,
											 'demandesContacts'=>$demandesContacts,
											 'nouveauMessages'=>$nouveauMessages,
											 'recommandationRequest'=>$recommandationRequest
										 ));
	}
	
	//Repondre a un message
	public function actionReply(){
		
		$model=new Messages;
		$this->performAjaxValidation($model);
		
		if(isset($_POST['id']))
		{
			$model->destinataire_id=$_POST['id'];
			$destinataire=$_POST['nom'].' '.$_POST['prenom'];
			$this->render('reply',array(
											'model'=>$model,
											'destinataire'=>$destinataire
									  ));
		}
			
			
			if(isset($_POST['Messages']))
			{
				
				$model->attributes=$_POST['Messages'];
				$model->date_envoie=Date('Y-m-d');
				$model->expediteur_id=Yii::app()->user->getID();
				$destinataire=Membres::model()->getViewIdInfo($model->destinataire_id);
				
				if($model->save())
				{
					$expediteur=Membres::model()->getViewIdInfo(Yii::app()->user->getID());
					
				
					//Send an email to notify $destinataire
					$mail= new YiiMailMessage;
					$mail->view='message';
					$mail->setBody(array('nom'=>$expediteur['nom'],'prenom'=>$expediteur['prenom'],'id'=>$expediteur['id']),'text/html');
					$mail->addTo($destinataire['email']);
					$mail->from=$expediteur['email'];
					$mail->subject=$model->objet;
					Yii::app()->mail->send($mail);
				
					$this->redirect(Messages::model()->getReceivedUrl());
				}	
			}
			
		
	}
	//Nouveau message a partir d'un profil
	public function actionComposeProfile()
	{
		
		
				$model=new Messages;
				$this->performAjaxValidation($model);
				
				$flag=true;
				
				if(isset($_POST['id']))
					$model->destinataire_id=$_POST['id'];
					
				
				if(isset($_POST['Messages']))
				{
			    	$flag=false;
					$model->attributes=$_POST['Messages'];
					$model->date_envoie=Date('Y-m-d');
					$model->expediteur_id=Yii::app()->user->getID();
					$destinataire=Membres::model()->getViewIdInfo($model->destinataire_id);
					
					if($model->save())
					{
						$expediteur=Membres::model()->getViewIdInfo(Yii::app()->user->getID());
						
						/**
						//Send an email to notify $destinataire
						$mail= new YiiMailMessage;
						$mail->view='message';
						$mail->setBody(array('nom'=>$expediteur['nom'],'prenom'=>$expediteur['prenom'],'id'=>$expediteur['id']),'text/html');
						$mail->addTo($destinataire['email']);
						$mail->from=$expediteur['email'];
						$mail->subject=$model->objet;
						Yii::app()->mail->send($mail);
						*/
						
						Yii::app()->end();
					}
					else
						$flag=true;
					
					
			    }		
			  
			   
			
			    if($flag)
			    {
			    	Yii::app()->clientScript->scriptMap['jquery.js']=false;
					$this->renderPartial('_composeProfile',array('model'=>$model),false,true);
			    }
		
	}
	

	//Reception des messages
	public function actionReceived()
	{
			$dataProvider=Messages::model()->loadReceived();

			//Inbox
			$demandesContacts=ContactMembres::model()->getDemandesCount();
			$nouveauMessages=Messages::model()->getNewMessagesCount();
			$recommandationRequest=Recommandations::model()->getRecommandationRequestCount();
			
			$this->render('received',array(
											'received'=>$dataProvider,
											'demandesContacts'=>$demandesContacts,
											'nouveauMessages'=>$nouveauMessages,
											'recommandationRequest'=>$recommandationRequest
										));
	}


	//Effacer un message		
	public function actionDelete()
	{
		
		if(isset(Yii::app()->request->isPostrequest))
		{
		
			if(isset($_POST['id']))
			{
				$id=$_POST['id'];
				$messages=$this->loadModel($id);	
				$id=$messages->expediteur_id;	
				$messages->delete();
			
				if($id===Yii::app()->user->getID())
				
					$this->redirect(Messages::model()->getSentUrl());
				
				else 
					$this->redirect(Messages::model()->getReceivedUrl());
			}
			else 	
				throw new CHttpException(400,'Requête invalide.');
		}
		
	}
	
	
	//Pour lire un message
	public function actionRead($id){
	
		//Reply to a message
		if(isset($_POST['Messages']) and Yii::app()->request->isPostRequest)
		{	
			$new= new Messages();
			$this->performAjaxValidation($new);
			$new->date_envoie=Date('Y-m-d H:i:s');
			$new->contenu=$_POST['Messages']['contenu'];
			$new->objet=$_POST['Messages']['objet'];
			$new->destinataire_id=$_POST['Messages']['destinataire_id'];
			$new->expediteur_id=Yii::app()->user->getID();

			
			if($new->validate() and $new->save())
			{
				$expediteur=Membres::model()->getViewIdInfo(Yii::app()->user->getID());
				$destinataire=Membres::model()->getViewIdInfo($new->destinataire_id);
				
					//Send an email to notify $destinataire
					$mail= new YiiMailMessage;
					$mail->view='message';
					$mail->setBody(array('nom'=>$expediteur['nom'],'prenom'=>$expediteur['prenom'],'id'=>$expediteur['id']),'text/html');
					$mail->addTo($destinataire['email']);
					$mail->from=$expediteur['email'];
					$mail->subject=$model->objet;
					Yii::app()->mail->send($mail);

				Yii::app()->user->setFlash('messageSent',"Message envoyé" );
				$this->redirect(Messages::model()->getReceivedUrl());
			}
		}
		
		if(isset($id) and is_numeric($id))
		{
			$reply= new Messages();
			$message=$this->loadModel($id);
			
			if($message->date_lecture == "" and $message->destinataire_id == Yii::app()->user->getID())
			{
				$message->date_lecture=date('Y-m-d H:i:s');
				$message->save();
			}
			
			$reply->objet=$message->objet;
			
			//If you request from Sent items or items received
			if($message->expediteur_id == Yii::app()->user->getID())
			$reply->destinataire_id=$message->destinataire_id;
			else
			$reply->destinataire_id=$message->expediteur_id;
			
			$reply->expediteur_id=Yii::app()->user->getID();

			//Loading conversation
			$objet=$message->objet;
			
			//If you request from Sent items or items received
			if($message->expediteur_id == Yii::app()->user->getID())
			$membre_id=$message->destinataire_id;
			else
			$membre_id=$message->expediteur_id;
			
			$conversationArray=Messages::model()->loadConversation($membre_id, $objet);
			
				
			//Making sure date_lecture is properly set for each message in the conversation.
			foreach ($conversationArray as $value)
			{
				$msgUpdate=$this->loadModel($value['messages_id']);
				
				if($msgUpdate->date_lecture == "" and $value['destinataire_id']== Yii::app()->user->getID())
				{
					$msgUpdate->date_lecture=date('Y-m-d H:i:s');
					$msgUpdate->save();
				}
			}
			
			$conversation = new CArrayDataProvider($conversationArray, array('keyField'=>'messages_id',));
			
			//Setting pager to last message received in the conversation.
			$pager=$conversation->pagination;
                $pager->itemCount=$conversation->totalItemCount;
                if(!Yii::app()->request->isAjaxRequest)
                        $pager->currentPage=$pager->pageCount;
			
			
		}
				
			//Inbox
			$demandesContacts=ContactMembres::model()->getDemandesCount();
			$nouveauMessages=Messages::model()->getNewMessagesCount();
			$recommandationRequest=Recommandations::model()->getRecommandationRequestCount();
			
			
			$this->render('read',array(
											'message'=>$message,
											'reply'=>$reply,
											'conversation'=>$conversation,

protected/modules/profil/views/default/_id.php
<?php $this->pageTitle=Yii::app()->name.' | '.ucwords($membre['prenom']).' '.strtoupper($membre['nom']);?>

<div id="demande-recomm" class="span-13 underline-link" align=left>
<?php 
	 
	  $this->renderPartial('_demandeRecomm',array('membre'=>$membre)); 
?>
</div>

<div class="span-4 card" align="center">

<?php 
if($membre['chemin_avatar']!=NUll)
{
echo CHtml::image($membre['chemin_avatar'],ucwords($membre['prenom']).' '.strtoupper($membre['nom']),array('width'=>150,'height'=>155));
}
?>
</div>

<div class="span-8" align="left">
<br>
<h3><?php echo ucwords($membre['prenom']).' '.strtoupper($membre['nom']);?></h3>
<i><?php echo Villes::itemByInteger($membre['ville']).', '.Pays::itemByInteger($membre['pays']);?></i>
<br><i><b><?php echo DomaineActivites::itemByInteger($membre['domaine_activite'])?></b></i>

<div class="span-8 underline-link" align="left">
<strong>
<?php 
	  if($membre['id']!=Yii::app()->user->getID())
	 	echo CHtml::link('Curriculum Vitae',ContactMembres::model()->getCvUrl($membre['id']));
	 else 
	 	echo CHtml::link('Mon CV',ContactMembres::model()->getCvUrl($membre['id']));
?>
</strong>
</div>

<div class="span-8 underline-link" align="left">
<strong>
<?php 
if($contactNombre>1)
echo CHtml::link($contactNombre.' contacts',$this->createUrl('contactMembres/contacts',array('id'=>$membre['id'])));
elseif($contactNombre==1)
echo Chtml::link('Un contact',$this->createUrl('contactMembres/contacts',array('id'=>$membre['id'])));
else
echo 'Z&eacute;ro contact';

?>
<br>
<?php 

echo $visiteNombre.' visite(s)';

/**
if($visiteNombre>1)
echo ' | '.$visiteNombre.' visites';
elseif($visiteNombre==1)
echo ' | Une visite';
else 
echo ' | Z&eacute;ro visite';

**/
?>
<br>
<?php 
if($membre['siteweb_entreprise']!=null)
echo CHtml::link($membre['siteweb_entreprise'],$membre['siteweb_entreprise']);
?>
</strong>
</div>
<div class="span-8 underline-link">
<?php 

	/**
	if(Yii::app()->user->getID()!=$membre['id'])
	 echo '<strong>'.CHtml::link('Envoyer un message','#',array('submit'=>array('messages/reply'),
	 															   'params'=>array(
	 															   					'id'=>$membre['id'],
	 																				'nom'=>$membre['nom'],
	 																				'prenom'=>$membre['prenom']
	 																			   )
													  )).'</strong>';
													  
	*/
?>
</div>
</div>



<div class="span-15">
<div class="span-15">
<br>
<h2>OBJECTIF</h2>
</div>

<?php
echo $membre['objectif']; 
?>
<br>

</div>

protected/modules/profil/views/default/_itemView.php

<div class="span-15 vcard" align="left">
<?php echo Membres::model()->getViewID($data['id'], $data['chemin_avatar'], $data['nom'], $data['prenom'], $data['domaine_activite']);?>
</div>


protected/modules/profil/views/default/_itemViewAppelOffres.php
<div class="row" align="left">
<div class="column" align="left">
<?php 

	echo AppelOffres::model()->getViewInfo($data['appelOffresId'], 
										   $data['titre'], $data['numero'], $data['date_fin']);

?>

</div>
<hr>
</div>

protected/modules/profil/views/default/_itemViewCv.php
<div class="span-16 vcard" align="left">
<?php echo Membres::model()->getViewCV($data['id'],$data['nom'], $data['prenom'], $data['domaine_activite']);?>
</div>


protected/modules/profil/views/default/_itemViewSuggest.php
<div class="span-7 vcard" align="left">
<?php echo Membres::model()->getViewID($data['id'], $data['chemin_avatar'], $data['nom'],$data['prenom'],$data['domaine_activite'])?>
</div>


protected/modules/profil/views/default/_recommandations.php
<div class="span-15">
<br>
<?php if($membre['id']==Yii::app()->user->getID())
	
			echo '<h2>MES RECOMMANDATIONS</h2>';
		else 	
			echo '<h2>RECOMMANDATIONS</h2>';

?>
</div>
<div class="span-15" align="left">
<?php 
	
	if($recommandations!=array()){

		foreach ($recommandations as $value){
?>
	
<div class="span-7" align="left">
<?php echo Membres::model()->getViewID($value['destinataire_id'], $value['chemin_avatar'], $value['nom'], $value['prenom'], $value['domaine_activite']);?>
</div>

<div class="span-7" align="left">
<?php echo $value['message'];?>
</div>
<hr>
<?php 
		
		}
	}
	else 
		echo 'Aucunes'
?>
</div>

protected/modules/profil/views/default/cv.php
<?php $this->pageTitle='CV | '.strtoupper($membre['nom']).' '.ucwords($membre['prenom']);?>
<div class="span-23">
<div class="span-16">
<div class="span-15 underline-link" align="right">
<?php 

	if(Yii::app()->user->getID()!=$membre['id'])
	 echo '<strong>'.CHtml::link('Envoyer un message','#',array('submit'=>array('messages/reply'),
	 															   'params'=>array(
	 															   					'id'=>$membre['id'],
	 																				'nom'=>$membre['nom'],
	 																				'prenom'=>$membre['prenom']
	 																			   )
													  )).'</strong>';
?>
</div>


<div class="span-15">
<h3>
<?php echo strtoupper($membre['nom']).' '.ucwords($membre['prenom']);?>
</h3>
<?php 
		
	  echo Villes::itemByInteger($membre['ville']).', '.Pays::itemByInteger($membre['pays']);

	  if($contactNombre!=0)
	  	echo ' - '.CHtml::link($contactNombre.' contact(s)',$this->createUrl('contactMembres/contacts',array('id'=>$membre['id'])));
	  else 
	  	echo ' - Zero contact';
?>
</div>


<div class="span-10">
<br>
<h2>OBJECTIF</h2>
</div>
<div class="span-15">
<?php
	echo $membre['objectif']; 
?>
<br>

</div>


<div class="span-15">
<?php 
	 //Profil already formated
	 include_once '_profil.php';
?>
</div>
</div>
<?php 
		if(!Yii::app()->user->isGuest)
		$this->renderPartial('_rightMenu',array('id'=>$membre['id'],'suggestMembres'=>$suggestMembres,'suggestGroups'=>$suggestGroups));
?>
<!-- end right menu -->
</div>

protected/modules/profil/views/default/update.php
<div class="span-16">
<div class="span-15">
<?php 
	$urlMembresImages=$this->createUrl('membres/uploadImage',array());
	echo '<strong>'.CHtml::link('Modifier',Membres::model()->getUpdateUrl()).'</strong> les informations personelles';
?>
<br>
<?php 
	echo '<strong>'.CHtml::link('Changer la photo',$urlMembresImages).'</strong> du profil';
?>
<br>
</div>

<div class="span-15">
<?php include_once '_id.php';?>
</div>


<div class="span-15">
<br>
<div class="span-10">
<h2>EXPERIENCES</h2>
</div>
<div class="span-10" align="right">
<?php echo CHtml::link('Ajouter',Experiences::model()->getCreateUrl(),array('class'=>'button')); ?>
</div>
<?php
	
	foreach ($experiences as $value) 
	{
			//Gestion de l'affichage de la date
			$dateDebut=Helper::dateProfileFormat($value['date_debut']);
			$dateFin=Helper::dateProfileFormat($value['date_fin']);	
	
?>


<div class="span-15" align="left">

<?php 
echo CHtml::link('Modifier',Experiences::model()->getUpdateUrl($value['id'])).
' | '.CHtml::link('Supprimer','#',array('submit'=>array('experiences/delete'),
		 								   'confirm'=>'Voulez-vous vraiment supprimer cet élément?',
		 								   'params'=>array('id'=>$value['id'])));
?>
<br>
<h3><?php echo CHtml::encode($value['entreprise']);?></h3>
</div>

<div class="span-15" align="left">
<h4><?php echo CHtml::encode($value['position']);?></h4>
</div>
<br>
<div class="span-15" align="left">
	<?php echo CHtml::encode($dateDebut).' - ';?>

	<?php
		   if($value['date_fin']===NULL or $value['date_fin']==='0000-00-00')
		   		
		   		echo 'Jusqu’à maintenant';
		   else
		   		echo CHtml::encode($dateFin);
	 ?>

</div>
<div class="span-15" align="left">
	 <?php echo CHtml::encode($value['adresse']);?>
</div>

<div class="span-15" align="left">
<br>
	 <?php echo $value['description'];?>

</div>

<br>
<?php  
	}
?>

<br>
<br>
<div class="span-15" align="left">
<br>
<div class="span-10">
<h2>EDUCATIONS</h2>
</div>
<div class="span-10" align="right">
<?php echo CHtml::link('Ajouter',Educations::model()->getCreateUrl(),array('class'=>'button'));?>
</div>
</div>

<?php
	foreach ($educations as $key=>$value) {
	
?>

<div class="span-15">
<?php 
	$dateDebut=Helper::dateProfileFormat($value['date_debut']);
	$dateFin=Helper::dateProfileFormat($value['date_fin']);		
?>
</div>
<div class="span-15" align="left">
<?php 
echo CHtml::link('Modifier',Educations::model()->getUpdateUrl($value['id'])).
' | '.CHtml::link('Supprimer','#',array('submit'=>array('educations/delete'),
		 								   'confirm'=>'Voulez-vous vraiment supprimer cet élément?',
		 								   'params'=>array('id'=>$value['id'])));
?>
<h3><?php echo CHtml::encode($value['ecole']).' ';?></h3>
</div>

<div class="span-15" align="left">
<h4><?php echo CHtml::encode($value['diplome']).' en '.CHtml::encode($value['domaine_etude']);?></h4>
</div>

<div class="span-15" align="left">
	<?php echo CHtml::encode($dateDebut).' - ';?>

	<?php
		   if($value['date_fin']===NULL or $value['date_fin']==='0000-00-00')
		   		
		   		echo 'jusqu’à maintenant';
		   else
		   		echo CHtml::encode($dateFin);
	 ?>
</div>

<div class="span-15" align="left">
<?php echo $value['competence_specifique'];?>
</div>


<br>

<?php  
	}
?>
<br>
<br>

<div class="span-15" align="left">
<br>
<div class="span-10">
<h2>INFORMATIONS ADDITIONNELLES </h2>
</div>
<div class="span-10" align="right">
<?php echo CHtml::link('Modifier',$this->createUrl('membres/update',array('id'=>$membre['id'])),array('class'=>'button'));?>
</div>
</div>
<br>

<div class="span-15" align="left">
<div class="span-3">
<strong>Pays</strong>
</div>
<div class="span-10" align="left">
<?php echo CHtml::encode(Pays::itemByInteger($membre['pays']));?>
</div>
</div>


<div class="span-15" align="left">
<div class="span-3">
<strong>Ville</strong>
</div>
<div class="span-10" align="left">
<?php echo CHtml::encode(Villes::itemByInteger($membre['ville']));?>
</div>
</div>



<div class="span-15" align="left">
<div class="span-3">
<strong>Site web</strong>
</div>
<div class="span-10" align="left">
<?php 
	
	if($membre['siteweb_entreprise']==='' or $membre['siteweb_entreprise']===null)
		echo CHtml::link('Ajouter',Membres::model()->getUpdateUrl());
	else 
		echo CHtml::encode($membre['siteweb_entreprise']);

?>
</div>
</div>



<div class="span-15" align="left">
<div class="span-3">
<strong>T&eacute;l&eacute;phone</strong>
</div>
<div class="span-10" align="left">
<?php 
	
	if($membre['telephone']==='' or $membre['telephone']===null)
		echo CHtml::link('Ajouter',Membres::model()->getUpdateUrl());
	else 
		echo CHtml::encode($membre['telephone']);

?>
</div>
</div>



<div class="span-15" align="left">
<div class="span-3">
<strong>Autres</strong>
</div>
<div class="span-10" align="left">
<?php 
	
	if($membre['info_additionel']==='' or $membre['info_additionel']===null)
		echo CHtml::link('Ajouter',Membres::model()->getUpdateUrl());
	else 
		echo $membre['info_additionel'];

?>
</div>
</div>



<div class="span-10">
<br>
<?php if($membre['id']==Yii::app()->user->getID())
	
			echo '<h2>MES RECOMMANDATIONS</h2>';
		else 	
			echo '<h2>RECOMMANDATIONS</h2>';

?>
<div class="span-15" align="left">
<?php 
	
	if($recommandations!=array()){

		foreach ($recommandations as $value){
?>
	
<div class="span-6" align="left">
<?php echo Membres::model()->getViewID($value['destinataire_id'], $value['chemin_avatar'], $value['nom'], $value['prenom'], $value['domaine_activite']);?>
</div>

<div class="span-8" align="left">
<?php echo $value['message'];?>
</div>
<div class="span-2" align="left">
	<?php echo CHtml::link('Effacer',"",array('submit'=>array('recommandations/deleteConfirm'),
											  'confirm'=>'Voulez-vous vraiment supprimer cet élément?',
											  'params'=>array('id'=>$value['recommandations_id'])));
	?>
</div>
<hr>
<?php 
		
		}
	}
	else 
		echo 'Aucunes'
?>
</div>
</div>
</div>
</div>
<?php $this->renderPartial('_rightMenu',array('id'=>$membre['id'],'suggestMembres'=>$suggestMembres,'suggestGroups'=>$suggestGroups));?>