protected/modules/groupes/models/Groupes.php
<?php

/**
 * This is the model class for table "{{groupes}}".
 *
 * The followings are the available columns in table '{{groupes}}':
 * @property string $id
 * @property string $nom
 * @property integer $domaine
 * @property string $description
 * @property string $chemin_avatar
 * @property string $date_creation
 * @property string $groupes_statut
 * @property string $groupes_actif
 * @property string $b_membres_id
 */
class Groupes extends CActiveRecord
{
	const STATUT_OUVERT = 'ouvert';
	const STATUT_FERME = 'ferme';
	
	public function getGroupesStatut() {
		
		return array(
			self::STATUT_OUVERT => 'Ouvert',
			self::STATUT_FERME => 'Fermé',
		);
	}
	public function getStatut()
	{
		if($this->groupes_statut == 'ouvert') return 'ouvert';
		else return 'ferme';
	}
	
	/**
	 * Returns the static model of the specified AR class.
	 * @return Groupes the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{groupes}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nom, domaine, groupes_statut', 'required'),
			array('nom', 'unique'),
			array('domaine', 'numerical', 'integerOnly'=>true),
			array('nom, chemin_avatar', 'length', 'max'=>60),
			array('description', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, nom, domaine, description, chemin_avatar, date_creation, groupes_statut, groupes_actif, b_membres_id', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		return array();
	}
	
	//Static function IsAdmin by groupes ID
	public static function getIsAdmin($id)
	{
		$result = Yii::app()->db
								->createCommand()
								->select('id','b_membres_id')
								->from('b_groupes')
								->where(array('and','id ='.$id,'b_membres_id='.Yii::app()->user->getID()))
								->queryRow();
		if($result===false)
			return false;
		else 
			return true;
	}
	
	
	
	public function getIsCreator() 
	{
	 
	 if(Yii::app()->user->id === $this->b_membres_id)
	 	return true;
	 else 
	 	return false;
	}
	
	public function getCommentCount() 
	{
	 	$count = Commentaires::model()->count('b_groupes_id = '.$this->id);
	 	return $count;
	}
	/*
	 *  groups of the current user
	 */
	public static function getMyGroups()
	{
		$result = Yii::app()->db
								->createCommand()
								->select('b_groupes.id g_id, b_groupes.nom g_nom, b_groupes.domaine g_domaine,b_groupes.b_membres_id g_admin, 
										  b_groupes.chemin_avatar g_avatar,b_groupes.groupes_statut g_statut')
								->from('b_contact_groupes')
								->where(array('and','b_contact_groupes.b_membres_id = '.Yii::app()->user->id, 'etat = \'accepte\''))
								->join('b_groupes', 'b_groupes.id = b_contact_groupes.b_groupes_id')
								->queryAll();
								
		return new CArrayDataProvider($result,array('keyField'=>'g_id', 'pagination'=> array('pageSize'=>10)));
	}
	
	public function getGroupesByID($id){
		
		$result = Yii::app()->db
								->createCommand()
								->select('b_groupes.id g_id, b_groupes.nom g_nom, b_groupes.domaine g_domaine, b_groupes.chemin_avatar g_avatar')
								->from('b_contact_groupes')
								->where(array('and','b_contact_groupes.b_membres_id = '.$id, 'etat = \'accepte\''))
								->join('b_groupes', 'b_groupes.id = b_contact_groupes.b_groupes_id')
								->queryAll();
		return $result;								
	}
	
	//Get all the groups available
	public function getGroups()
	{
		$groups=Yii::app()->db->createCommand()
			->select('b_groupes.id g_id, b_groupes.nom g_nom, b_groupes.domaine g_domaine, b_groupes.chemin_avatar g_avatar, b_groupes.groupes_statut g_statut')
			->from('b_groupes')
			->order('g_nom ASC')
			->queryAll();
		
		return $groups;
	}
	
	/*
	 *  add a comment
	 */
	public function addComment($comment) 
	{
		$comment->b_groupes_id = $this->id;
		$comment->b_membres_id = Yii::app()->user->id;
		$comment->date_creation = date('Y-m-d H:i:s');
		
		return $comment->save();
	}
	
	//get owner by group id
	public function getOwnerByGroupId($id)
	{
		$result = Yii::app()->db
								->createCommand()
								->select('b_groupes.nom g_nom, b_membres.id owner_id, b_membres.nom owner_nom, b_membres.prenom owner_prenom, b_membres.email owner_email')
								->from('b_groupes')
								->where('b_groupes.id = '.$id)
								->join('b_membres', 'b_membres.id = b_groupes.b_membres_id')
								->queryRow();
		return $result;
	}
	/*
	 *  owner of the group
	 */
	public function getOwner()
	{
		$result = Yii::app()->db
								->createCommand()
								->select('b_membres.id owner_id, b_membres.nom owner_nom, b_membres.prenom owner_prenom')
								->from('b_groupes')
								->where('b_groupes.id = '.$this->id)
								->join('b_membres', 'b_membres.id = b_groupes.b_membres_id')
								->queryRow();
		return $result;
	}
	/*
	 *  comments of a group
	 */
	public function getComments()
	 {
		
		$comments = Yii::app()->db
								->createCommand()
								->select('b_commentaires.id c_id, b_membres.id m_id, date_creation, message,b_groupes_id, nom, prenom, chemin_avatar, domaine_activite')
								->from('b_commentaires')
								->where('b_groupes_id = '.$this->id)
								->join('b_membres', 'b_membres.id = b_commentaires.b_membres_id')
								->order('date_creation DESC')
								->queryAll();
			
			$dataProvider= new CArrayDataProvider($comments, array('keyField'=>'c_id','pagination'=>array('pageSize'=>10)));
			$dataProvider->sort->defaultOrder='date_creation DESC';
			return $dataProvider;
	}
	/*
	 *  is a group member?
	 */
	public function isGroupMember($id) {
		
		$member = array();
		
		if(!Yii::app()->user->isGuest)
		{
			$userId=Yii::app()->user->getID();
			$member = Yii::app()->db
								->createCommand()
								->select('etat')
								->from('b_contact_groupes')
								->where(array('and','b_groupes_id = '.$id,' b_membres_id = '.$userId))
								->queryRow();
								
		}
		
		return $member;	
	}
	/*
	 *  total members of this group
	 */
	public function getMemberCount() {
		return ContactGroupes::model()->count('b_groupes_id = '.$this->id.' and etat = \'accepte\'');
	}
	/*
	 *  total member's requets for this group 
	 */
	public function getMemberRequestCount()
	{
		return ContactGroupes::model()->count('b_groupes_id = '.$this->id.' and etat = \'envoye\'');
	}
	/*
	 *  member's requets for this group 
	 */
	public function getMemberRequests() 
	{
		$memberRequest = array();
		
		$memberRequest = Yii::app()->db
								->createCommand()
								->select('b_membres.id m_id, b_contact_groupes.b_groupes_id g_id, etat, nom, prenom,chemin_avatar,domaine_activite')
								->from('b_contact_groupes')
								->where(array('and','b_groupes_id = '.$this->id,'etat = \'envoye\''))
								->join('b_membres','b_membres.id = b_contact_groupes.b_membres_id')
								->queryAll();
								
		
		
		return $memberRequest;	
	}
	/*
	 *  members of this group
	 */
	public function getMembers() {
		$members = array();
		
		$members = Yii::app()->db->createCommand()
								->select('b_membres.id m_id, nom, prenom,chemin_avatar,domaine_activite')
								->from('b_contact_groupes')
								->where(array('and','b_groupes_id = '.$this->id,'etat = \'accepte\''))
								->join('b_membres','b_membres.id = b_contact_groupes.b_membres_id')
								->queryAll();
								
		
		
		return $members;			
	}
	
		
	//members email
	public function getMembersEmail(){
		
		$members = array();
		
		$members = Yii::app()->db->createCommand()
								->select('b_membres.id m_id,email')
								->from('b_contact_groupes')
								->where(array('and','b_groupes_id = '.$this->id,'etat = \'accepte\''))
								->join('b_membres','b_membres.id = b_contact_groupes.b_membres_id')
								->queryAll();
								
		
		
		return $members;	
	}
	
	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(		
			'nom' => 'Nom du groupe',
			'domaine' => 'Secteur d\'activite',
			'description' => 'Description',			
			'date_creation' => 'Date Creation',
			'groupes_statut' => 'Type de groupe',
			'b_membres_id' => 'Administrateur',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('nom',$this->nom,true);
		$criteria->compare('domaine',$this->domaine);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('chemin_avatar',$this->chemin_avatar,true);
		$criteria->compare('date_creation',$this->date_creation,true);
		$criteria->compare('groupes_statut',$this->groupes_statut,true);
		$criteria->compare('groupes_actif',$this->groupes_actif,true);
		$criteria->compare('b_membres_id',$this->b_membres_id,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	/*
	 *  @override CActiveRecord::beforeSave()
	 */
	protected function beforeSave() {
		if($this->isNewRecord) {
			$this->date_creation = date('Y-m-j');
			$this->b_membres_id = Yii::app()->user->id;
		
		}

protected/modules/groupes/controllers/CommentairesController.php
<?php

class CommentairesController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('deny',
				'actions'=>array('delete'),
				'users'=>array('?'),
			),
			array('allow', 
				'actions'=>array('view'),
				'users'=>array('?'),
			),
			array('allow', 
				'actions'=>array('delete','view'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}


	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete()
	{
			
		if(Yii::app()->request->isPostRequest)
		{	
			if(isset($_POST['id']))
			{
				$id=$_POST['id'];
				$model=$this->loadModel($id);
			
				if($model->b_membres_id===Yii::app()->user->getID() or Groupes::getIsAdmin($model->b_groupes_id))
				{
					$group_id=$model->b_groupes_id;
					$model->delete();
					$this->redirect(Groupes::model()->getViewUrl($group_id));
				
				}
				else 
					throw new CHttpException(400,'Requête invalide.');
			}
				
		}
		else
			throw new CHttpException(400,'Requête invalide.');
	}

	//Public view for single comment because of Facebook like.	
	public function actionView($id)
	{
		$comment=Commentaires::model()->getComment($id);
		$groupe=Groupes::model()->findByPk($comment['g_id']);

		$this->render('application.modules.groupes.views.groupes._comments',array('data'=>$comment,'groupe'=>$groupe));
	}
	
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Commentaires::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'La page demandée n’existe pas.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='commentaires-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/groupes/views/groupes/_addComment.php
<?php 
$members = $model->members;
$isMember = false;

foreach ($members as $member) {
	if($member['m_id']=== Yii::app()->user->id) {
		$isMember = true;
		break;
	}
}
if($isMember) :
?>

<br><br><br>
<strong>Ajouter un commentaire</strong>

<?php if(Yii::app()->user->hasFlash('commentSubmited')) : ?>
<div class="flash-success">
<?php echo Yii::app()->user->getFlash('commentSubmited'); ?>
</div>
<?php endif; ?>
<?php $this->renderPartial('/commentaires/_form',array(
'model'=>$comment,
)); 
endif;?>

protected/modules/groupes/views/groupes/_comments.php
<?php 
if(isset($groupe))
{
	$this->pageTitle=Yii::app()->name.' | Groupe '.$groupe->nom;
	$this->renderPartial('application.modules.groupes.views.groupes._groupeinfo',array('model'=>$groupe));
	echo '<div class="span-15"><br><br></div>';
}
?>
<!-- Groupe info -->

<div class="span-15 comments">
	<div class="span-2" align="left">
	<?php 
	 echo CHtml::link(CHtml::image($data['chemin_avatar'],$data['prenom'].' '.$data['nom'],array(
																			'width'=>70,
																			'height'=>70,
																		)),ContactMembres::model()->getViewUrl($data['m_id']));
	
	?>
	</div>
	<div class="span-12" align="left">
	<div class="span-6" align="left">
	<h4>
	<?php 
	echo CHtml::link(ucwords($data['prenom']).' '.strtoupper($data['nom']),ContactMembres::model()->getViewUrl($data['m_id']));
	?>
	</h4>
	</div>
	<div class="span-5" align="right">
	<?php echo Yii::app()->dateFormatter->format("dd MMMM y, HH:mm", $data['date_creation']); ?>
	</div>
	<div class="span-12" align="left">
	<?php echo CHtml::encode($data['message']); ?>
	</div>
	
	<div class="span-12" align="right">
	<br>
	<?php 
	
		if($data['m_id']===Yii::app()->user->getID())
			echo CHtml::link('Effacer','#',array('submit'=>array('commentaires/delete'),
												 'params'=>array('id'=>$data['c_id']),
												 'confirm'=>'Voulez-vous vraiment supprimer cet élément ?'));
	?>
	</div>
	</div>
	
	<div class="span-8" align="left">
	<br>
	
	</div>
</div>
<!-- commentaire -->
<?php Yii::app()->clientScript->registerScript($data['c_id'],'FB.XFBML.parse()',CClientScript::POS_END);?>

protected/modules/groupes/views/groupes/_commentsAdmin.php
<div class="span-15">
	<div class="span-6" align="left">
	<?php echo Membres::model()->getViewID($data['m_id'], $data['chemin_avatar'], $data['nom'],$data['prenom'],$data['domaine_activite']) ?> 
	</div>
	<div class="span-8" align="left">
	<div class="span-3">
	<br>
	<strong><?php echo Helper::dateViewFormat($data['date_creation']); ?></strong>
	</div>
	<div class="span-3" align="right">
	<br>
	<?php 
	
		if($data['m_id']===Yii::app()->user->getID())
			echo CHtml::link('Effacer','#',array('submit'=>array('commentaires/delete'),
												 'params'=>array('id'=>$data['c_id']),
												 'confirm'=>'Voulez-vous vraiment supprimer cet élément ?'));
	?>
	</div>
	</div>
	
	<div class="span-8" align="left">
	<br>
	<?php echo CHtml::encode($data['message']); ?>
	</div>
		
	<hr>
</div>
<!-- commentaire -->

protected/modules/groupes/views/groupes/_form.php
<div class="wide form">

<?php 
		$form=$this->beginWidget('CActiveForm', array(
														'id'=>'groupes-form',
														'enableAjaxValidation'=>true,
								)); 
?>
<div class="span-13" align="left">
	
	<p class="note">Les champs avec <span class="required">*</span> sont obligatoire</p>
	<?php echo $form->errorSummary($model); ?>
	
	
</div>


<div class="span-16" align="left">


	<div class="span-16">
	<?php echo $form->error($model,'nom'); ?>
	</div>
	<div class="span-16">
		<?php echo $form->labelEx($model,'nom'); ?>
		<?php echo $form->textField($model,'nom',array('size'=>25,'maxlength'=>25)); ?>
		
	</div>





	<div class="span-16">
	<?php echo $form->error($model,'domaine'); ?>
	</div>
	<div class="span-16">
		<?php echo $form->labelEx($model,'domaine'); ?>
		<?php echo $form->dropDownList($model,'domaine', DomaineActivites::loadItems(),array('prompt'=>'Sélectionnez:')); ?>
	</div>
	
	
	
	
	
	<div class="span-16">
	<?php echo $form->error($model,'groupes_statut'); ?>
	</div>
	<div class="span-16">
		<?php echo $form->labelEx($model,'groupes_statut'); ?>
		<?php echo $form->dropDownList($model,'groupes_statut', $model->groupesStatut); ?>
	</div>





	<div class="span-16">
	<?php echo $form->error($model,'description'); ?>
	</div>
	<div class="span-16">
		<?php echo $form->labelEx($model,'description'); ?>
		<?php echo $form->textArea($model,'description',array('cols'=>55,'rows'=>8));?>
	</div>

</div>
<div class="span-13" align="right">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Créer ' : 'Sauvegarder',array('class'=>'button')); 
				echo '  ou  '.CHtml::link('Annuler',ContactMembres::model()->getUpdateUrl(Yii::app()->user->Id));
		 
		?>
</div>
<?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/groupes/views/groupes/_groupeinfo.php
<div class="span-15 card">
<div class="span-3" align="left">
<?php if($model->chemin_avatar !== null) 
	echo CHtml::image($model->chemin_avatar,$model->nom,array('width'=>100, 'height'=>80));
?>
</div>

<div class="span-10" align="left">
<?php echo '<h3>'.$model->nom.'</h3>';?>
</div>
<br>
<div class="span-6" align="left">
<?php echo DomaineActivites::itemByInteger($model->domaine).' | '.
		   Helper::statutViewFormat($model->statut);?>
</div>
<div class="fb-like span-2" data-send="false" data-layout="button_count" data-width="50" data-show-faces="false" data-action="recommend" data-font="arial"></div>

<div class="span-10" align="left">
<i>
<?php $owner = $model->owner;
	echo 'Proprietaire : '.CHtml::link($owner['owner_prenom'].' '.$owner['owner_nom'],Yii::app()->createUrl('profil/default/view',array('id'=>$owner['owner_id'])));
?>
</i>
</div>

<div class="span-10" align="left">
<i>
<?php
		if($model->memberCount > 1) echo CHtml::link($model->memberCount.' membres', $this->createUrl('groupes/members', array('group_id'=>$model->id)));
		else echo CHtml::link($model->memberCount.' membre',$this->createUrl('groupes/members', array('group_id'=>$model->id)));
?>
</i>
</div>
</div>


protected/modules/groupes/views/groupes/_joinGroup.php
<?php
$_state = Groupes::model()->isGroupMember($group_id);
if(!$_state) {
 echo CHtml::ajaxButton('Rejoindre le groupe', ContactGroupes::model()->getCreateUrl($group_id),array('update'=>'#join-group'),array('class'=>'button'));
}
else {
	if($_state['etat'] === 'envoye') {
		echo 'Demande en cours de confirmation...';
	}}
?>

protected/modules/groupes/views/groupes/_memberRequests.php

<div class="container" align="left">
<div class="span-18" align="left">
<div class="span-7">
	<?php 	
	echo Membres::model()->getViewID($data['m_id'], $data['chemin_avatar'], $data['nom'],$data['prenom'],$data['domaine_activite']);
	?> 
</div>

<div id="accept-decline-request" class="span-2" align="center">
<br>
<?php 
	echo CHtml::link('Accepter', $this->createUrl('groupes/acceptNewMember', array('group_id'=>$data['g_id'], 'member_id'=>$data['m_id'])));
?>
</div>
<div class="span-2" align="center">
<br>
<?php 
	echo CHtml::link('Decliner', $this->createUrl('groupes/declineNewMember', array('group_id'=>$data['g_id'], 'member_id'=>$data['m_id'])));
?>
</div>
<hr>
</div>
</div>


protected/modules/groupes/views/groupes/_members.php
<div class="span-16">
<div class="span-10 vcard" align="left">
<?php 	
	echo Membres::model()->getViewID($data['m_id'], $data['chemin_avatar'], $data['nom'],$data['prenom'],$data['domaine_activite']);
?> 
</div>
</div>

protected/modules/groupes/views/groupes/groups.php
<?php $this->pageTitle=Yii::app()->name.' | Groupes de discussions';?>
<div class="span-23" align="left">
<div class="span-16">
<div class="span-16">
<h2>Les groupes de discussions</h2>
<?php echo CHtml::link('Creer un groupe',Groupes::model()->getCreateUrl(),array('class'=>'button'));?>
</div>
<div class="span-16" align="left">
<?php
		$this->widget('zii.widgets.CListView',
					 	array(
  					  			'dataProvider'=>$groups,
   					  			'itemView'=>'_itemViewGroups', 
					 	     )
					 );
			
	
?>

</div>
</div>

<?php $this->renderPartial('application.modules.profil.views.default._rightMenu',array('id'=>Yii::app()->user->getID(),'suggestMembres'=>$suggestMembres,'suggestGroups'=>$suggestGroups));?>
<!-- end right menu -->
</div>

protected/modules/groupes/views/groupes/memberRequests.php
<br>
<div class="container" align="left">
<div class="span-18">
<h2><?php echo 'Demandes d\'adhésion à <font size="10px">'.CHtml::link($model->nom,$this->createUrl('groupes/view',array('id'=>$model->id))).'</font>'; ?></h2><hr>
</div>
<div class="span-18">
<?php
		$this->widget('zii.widgets.CListView',
					 	array(
  					  		'dataProvider'=>$memberRequests,
   					  		'itemView'=>'_memberRequests', 
					 	     )
					 );
			
	
?>
</div>
</div>

protected/modules/groupes/views/groupes/myGroups.php
<?php $this->pageTitle=Yii::app()->name.' | Mes groupes';?>
<div class="span-23" align="left">
<div class="span-16">
<h2>Mes groupes</h2>
<?php echo CHtml::link('Creer un groupe',Groupes::model()->getCreateUrl(),array('class'=>'button'));?>
<div class="span-16" align="left">
<?php
		$this->widget('zii.widgets.CListView',
					 	array(
  					  		'dataProvider'=>$my_groups,
   					  		'itemView'=>'_myGroups', 
					 	     )
					 );
			
	
?>
</div>
</div>

<?php $this->renderPartial('application.modules.profil.views.default._rightMenu',array('id'=>Yii::app()->user->getID(),'suggestMembres'=>$suggestMembres,'suggestGroups'=>$suggestGroups));?>
<!-- end right menu -->
</div>

protected/modules/groupes/views/groupes/update.php
<div class="container" align="center">
<div class="span-18" align="left">
<h2>Modifier un groupe</h2><hr>
</div>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

</div>

protected/modules/groupes/views/groupes/view.php
<?php $this->pageTitle=Yii::app()->name.' | Groupe '.$model->nom;?>
<div class="span-23">
<div class="span-16">
<?php 
$this->renderPartial('_view',array(
											'model'=>$model,
											'comment'=>$comment,
											'suggestGroups'=>$suggestGroups
								  ));

?>
</div>
<!-- end group view -->


<?php 	
		if (!Yii::app()->user->isGuest)
		$this->renderPartial('application.modules.profil.views.default._rightMenu',array('id'=>Yii::app()->user->getID(),'suggestMembres'=>$suggestMembres,'suggestGroups'=>$suggestGroups));
?>
</div>

protected/modules/groupes/views/groupes/viewAdmin.php
<div class="span-23">

<div class="span-6" align="left">
<?php //echo CHtml::link('Changer le logo',Groupes::model()->getUploadImageUrl($model->id));?>
<?php echo CHtml::link('Modifier les informations',Groupes::model()->getUpdateUrl($model->id));?>
<?php //echo '<span style="color:red;font-weight:bold;">'.' | '.'</span>';?>
<?php //echo CHtml::link('Voir le profil',Groupes::model()->getViewUrl($model->id));?>

<?php /*if($model->isCreator and $model->statut == 'ferme') 
	  		{
	  			echo CHtml::link('Demandes d\'adhésion  ('.$model->memberRequestCount.')',$this->createUrl('groupes/memberRequests',array('group_id'=>$model->id)));
	  		}
	  	*/
?>
</div>
<br>
<?php 

$this->renderPartial('_view',array(
											'model'=>$model,
											'comment'=>$comment,
											'suggestGroups'=>$suggestGroups
		
								  ));

?>
</div>