protected/modules/profil/models/Statuts.php
<?php

/**
 * This is the model class for table "{{statuts}}".
 *
 * The followings are the available columns in table '{{statuts}}':
 * @property string $id
 * @property string $statut
 * @property string $date
 * @property string $newsId
 * @property string $b_membres_id
 */
class Statuts extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @return Statuts the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{statuts}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('statut, b_membres_id', 'required'),
			array('statut', 'length', 'max'=>140),
			array('b_membres_id', 'length', 'max'=>10),
			array('date', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, statut, date, newsId, b_membres_id', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'statut' => 'Statut',
			'date' => 'Date de publication',
		);
	}
	
	//Get statuts index
	public function getStatutsIndex(){
		
		//Array to construct data provider  with all articles in the network
		$statutsFeed=array();
		$arrayOfArray=array();
		
		//Load my contacts ID
		$contactsId=ContactMembres::model()->contacts(Yii::app()->user->getID());
		
		//Load my statuts
		$arrayOfArray[]=$this->getStatuts(Yii::app()->user->getID());
		
		//Load array of statuts for each contact
		foreach ($contactsId as  $value) {
			$arrayOfArray[]=$this->getStatuts($value);
		}
		
		//construct a single array with all statuts
		foreach ($arrayOfArray as  $value){
			
			foreach ($value as $statut){
				
				$statutsFeed[]=$statut;
			}
		}
		
		return $statutsFeed;
	}
	
	//Get statuts
	public function getStatuts($id)
	{
		
		 $statutsArray=Yii::app()->db->createCommand()
										->select('b_statuts.id,statut,b_membres_id,date,newsId,
												  b_membres.id m_id,b_membres.chemin_avatar m_avatar,nom,prenom,domaine_activite')
										->from('b_statuts')
										->where('b_membres_id='.$id)
										->join('b_membres','b_membres_id=b_membres.id')
										->order('date DESC')
										->queryAll();				
		return $statutsArray;
	}
	
	//Create URL
	public function getCreateUrl(){
		
		return Yii::app()->createUrl('profil/statuts/create',array());
	}
	//View URL
	public function getViewUrl($id){
		
		return Yii::app()->createUrl('profil/statuts/view',array('id'=>$id));
	}
	
	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('statut',$this->statut,true);
		$criteria->compare('date',$this->date,true);
		$criteria->compare('newsId',$this->newsId,true);
		$criteria->compare('b_membres_id',$this->b_membres_id,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
}

protected/modules/profil/controllers/StatutsController.php
<?php

class StatutsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('deny', 
				'actions'=>array('index','create','update','delete','comment'),
				'users'=>array('?'),
			),
			array('allow',
				'actions'=>array('view'),
				'users'=>array('?'),
			),
			array('allow',
				'actions'=>array('index','view','create','update','delete','comment'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	
	//Commentaires
	public function actionComment($id)
	{
		if(isset($id) and is_numeric($id))
		{
			if(Yii::app()->request->isAjaxRequest)
				$this->renderPartial('application.modules.profil.views.statuts._comment',array('id'=>$id),false,true);
				Yii::app()->end();	
		}
		
	}
	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$setTitle=true;
		$this->render('_view',array(
										'data'=>$this->loadModel($id),
										'setTitle'=>$setTitle,
									));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Statuts;

		// Uncomment the following line if AJAX validation is needed
		 //

		if(isset($_POST['Statuts']))
		{
			$this->performAjaxValidation($model);
			$model->attributes=$_POST['Statuts'];
			$model->date=date('Y-m-d H:i:s');
			$model->b_membres_id=Yii::app()->user->getID();
			
			if($model->save())
			{
				//$this->redirect(array('view','id'=>$model->id));
				$this->redirect(ContactMembres::model()->getIndexUrl());
			}
			
			$this->redirect(ContactMembres::model()->getIndexUrl());
		}

		//$this->render('create',array('model'=>$model,));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Statuts']))
		{
			$model->attributes=$_POST['Statuts'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			if(isset($_POST['id']) and is_numeric($_POST['id']))
			{
				$id=$_POST['id'];
				// we only allow deletion via POST request
				$this->loadModelAdmin($id)->delete();
				$this->redirect(ContactMembres::model()->getIndexUrl());
			}
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Statuts');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		 $statutArray=Yii::app()->db->createCommand()
										->select('b_statuts.id,statut,b_membres_id,date,newsId,
												  b_membres.id m_id,b_membres.chemin_avatar m_avatar,nom,prenom,domaine_activite')
										->from('b_statuts')
										->where('b_statuts.id='.$id)
										->join('b_membres','b_membres_id=b_membres.id')
										->order('date DESC')
										->queryRow();		
		if($statutArray===null)
			throw new CHttpException(404,'Requête invalide.');
		return $statutArray;
	}
	
	//Load model admin
	public function loadModelAdmin($id)
	{
		$model=Statuts::model()->findByPk($id);
		if($model===null or $model->b_membres_id!=Yii::app()->user->getID())
			throw new CHttpException(404,'Requête invalide.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='statuts-form')
		{
			CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/profil/views/statuts/_comment.php
<div id="fb-root"></div>
<script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
<div class="fb-comments" data-width="470" data-num-posts="10" data-colorscheme="light">
<fb:comments href="http://www.branchew.com<?php echo Statuts::model()->getViewUrl($id);?>" num_posts="3" width="500" style="padding-top: 20px; margin-top: 20px; border-top: 1px dotted grey;">
</fb:comments>
<?php Yii::app()->clientScript->registerScript($id,'FB.XFBML.parse()',CClientScript::POS_END);?>
</div>

protected/modules/profil/views/statuts/_view.php
<?php Yii::app()->clientScript->registerMetaTag($data['statut'],'Description')?>
<meta property="og:title" content="<?php echo 'Branchew statut | '.$data['statut'];?>"/>
<meta property="og:type" content="Picture"/>
<meta property="og:image" content="http://www.branchew.com<?php echo $data['m_avatar'];?>"/>
<meta property="og:description" content="<?php echo $data['statut'];?>"/>
<?php 
		if(isset($setTitle))
			$this->pageTitle='Branchew | '.$data['statut'];
?>
<div class="span-2" align="right">
<?php 
echo CHtml::link(CHtml::image($data['m_avatar'],$data['prenom'].' '.$data['nom'],array(
																			'width'=>50,
																			'height'=>50,
																		)),ContactMembres::model()->getViewUrl($data['m_id']));
?>																		
</div>
<div class="span-12">
<div class="span-8"><h4>
<?php 
 echo CHtml::link(ucwords($data['prenom']).' '.strtoupper($data['nom']),ContactMembres::model()->getViewUrl($data['m_id']));
?>
</h4></div>
<div class="span-10">
<?php echo $data['statut'];?>
</div>
<div class="span-1" align="right">
<div class="fb-like" data-href="http://www.branchew.com<?php echo Statuts::model()->getViewUrl($data['id']);?>" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false"></div>
</div>
<div class="span-13">
<div class="span-5" align="left">
<?php echo 'le '.Yii::app()->dateFormatter->format("dd MMMM y, HH:mm", $data['date']);?>
</div>
<div id="<?php echo $data['id'];?>" class="span-8" align="left">

<?php
		
	  if(!Yii::app()->user->isGuest)
	  echo CHtml::link('Commenter', '#',
                    array('onClick'=>' {'.CHtml::ajax(
                        array(
                                'update'=>'#'.$data['id'],
                                'url'=>Yii::app()->createUrl('profil/statuts/comment',array('id'=>$data['id'])),
                                'type'=>'GET',),
                                        array('live'=>false, 'id'=>$data['id'],)

                                            ).' return false; }'

                        ));
?>
<?php //echo CHtml::ajaxLink('Commenter',Yii::app()->createUrl('profil/statuts/comment',array('id'=>$data['id'])),array('update'=>'#'.$data['id']));?>
</div>

<div class="span-3" align="left">
<?php 
	  if($data['b_membres_id']==Yii::app()->user->getID())
	  echo CHtml::link('Supprimer','#',array('submit'=>array('statuts/delete'),
													   'params'=>array('id'=>$data['id']),
													   'confirm'=>'Voulez-vous vraiment supprimer?'
								 ));						 
?>
</div>
</div>
</div>