protected/modules/profil/models/Articles.php
<?php

/**
 * This is the model class for table "{{articles}}".
 *
 * The followings are the available columns in table '{{articles}}':
 * @property string $id
 * @property string $titre
 * @property string $chemin_avatar
 * @property string $contenu
 * @property string $date
 * @property string $actif
 * @property string $b_membres_id
 */
class Articles extends CActiveRecord
{
	const STATUS_DRAFT='false';
    const STATUS_PUBLISHED='true';
    const STATUS_ARCHIVED='review';
	/**
	 * Returns the static model of the specified AR class.
	 * @return Articles the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{articles}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('titre, contenu, b_membres_id', 'required'),
			array('titre', 'length', 'max'=>100),
			array('chemin_avatar', 'length', 'max'=>60),
			 array('actif', 'in', 'range'=>array('true','false','review')),
			array('date', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, titre, contenu, date, actif', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'titre'=>'Titre',
			'contenu' => 'Contenu',
			'date' => 'Date de publication',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('titre',$this->titre,true);
		$criteria->compare('contenu',$this->contenu,true);
		$criteria->compare('date',$this->date,true);
		$criteria->compare('actif',$this->actif,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}
	
	
	
	//Get articles index
	public function getArticlesIndex(){
		
		//Array to construct data provider  with all articles in the network
		$articlesFeed=array();
		$arrayOfArray=array();
		
		//Load my contacts ID
		$contactsId=ContactMembres::model()->contacts(Yii::app()->user->getID());
		
		//Load my articles
		$arrayOfArray[]=Articles::model()->getPublishedArticles(Yii::app()->user->getID());
		
		//Load array of acticles for each contact
		foreach ($contactsId as  $value) {
			$arrayOfArray[]=Articles::model()->getPublishedArticles($value);
		}
		
		//construct a single array with all articles
		foreach ($arrayOfArray as  $value){
			
			foreach ($value as $article){
				
				$articlesFeed[]=$article;
			}
		}
		
		return $articlesFeed;
	}
	
	
	//Get articles
	public function getArticles($id)
	{
		
		 $articlesArray=Yii::app()->db->createCommand()
										->select('id,chemin_avatar,titre,b_membres_id,actif,date')
										->from('b_articles')
										->where('b_membres_id='.$id)
										->order('date DESC')
										->queryAll();					
		return $articlesArray;
	}
	
	//Get published articles
	public function getPublishedArticles($id)
	{
		
		 $articlesArray=Yii::app()->db->createCommand()
										->select('b_articles.id,b_articles.chemin_avatar,titre,b_membres_id,b_articles.actif,date,newsId,
												  b_membres.id m_id,b_membres.chemin_avatar m_avatar,nom,prenom,domaine_activite')
										->from('b_articles')
										->where(array('and','b_membres_id='.$id,'b_articles.actif=true'))
										->join('b_membres','b_membres_id=b_membres.id')
										->order('date DESC')
										->queryAll();				
		return $articlesArray;
	}
	
	//View articles URL
	public function getViewArticlesUrl($id)
	{
		return Yii::app()->createUrl('profil/articles/viewArticles',array('id'=>$id));
	}
	
	//Create URL
	public function getCreateUrl()
	{
		return Yii::app()->createUrl('profil/articles/create',array());
	}
	
	//Publish URL
	public function getPublishUrl($id)
	{
		return Yii::app()->createUrl('profil/articles/publish',array('id'=>$id));
	}
	
	//Unpublish URL
	public function getUnpublishUrl($id)
	{
		return Yii::app()->createUrl('profil/articles/unPublish',array('id'=>$id));
	}
	
	//Update URL
	public function getUpdateUrl($id)
	{
		return Yii::app()->createUrl('profil/articles/update',array('id'=>$id));
	}
	
	//View URL
	public function getViewUrl($id)
	{
		return Yii::app()->createUrl('profil/articles/view',array('id'=>$id));
	}
	
	//Upload URL
	public function getUploadImageUrl($id)
	{
		return Yii::app()->createUrl('profil/articles/uploadImage',array('id'=>$id));
	}
}

protected/modules/profil/controllers/ArticlesController.php
<?php

class ArticlesController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('deny',
				'actions'=>array('index','create','update','delete','uploadImage','viewArticles','publish','unPublish'),
				'users'=>array('?'),
			),
			array('allow', 
				'actions'=>array('view'),
				'users'=>array('?'),
			),
			array('allow', 
				'actions'=>array('index','view','create','update','delete','uploadImage','viewArticles','publish','unPublish'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model=$this->loadModel($id);
		
		//If an article is not published, only you can see it
		if($model->actif==Articles::STATUS_DRAFT and $model->b_membres_id!=Yii::app()->user->getID())
			throw new CHttpException(404,'Requête invalide.');
			
		 $author=Membres::model()->membreInfoById($model->b_membres_id);
		
		if(!Yii::app()->user->isGuest)
		{
			//Suggest group
			$suggestGroups=ContactGroupes::model()->getSuggest();

			//Suggest contacts to user
			$suggestContacts=array();
 			$suggestId=array();
 			$suggestId=ContactMembres::model()->getSuggestIndex();
 		
 			if($suggestId!=array())
 			{	
 											
				 foreach ($suggestId as $value)
				 {
						$suggestContacts[$value]=ContactMembres::model()->queryContact($value);
												
				 }
			}
			
			$this->render('view',array(
											 'model'=>$model,
											 'suggestGroups'=>$suggestGroups,
											 'suggestMembres'=>$suggestContacts,	
											 'author'=>$author
							  ));
		}
		else
			$this->render('view',array(
											'model'=>$model,
											'author'=>$author
						 ));
		
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		
			$model=new Articles;
			$model->b_membres_id=Yii::app()->user->getID();
		
			// Uncomment the following line if AJAX validation is needed
			 $this->performAjaxValidation($model);

			if(isset($_POST['Articles']))
			{
				$model->attributes=$_POST['Articles'];
				$model->contenu=$_POST['contenu'];
				$model->date=date('Y-m-d H:i:s');
				$model->actif=Articles::STATUS_DRAFT;

				if($model->save())
					$this->redirect(array('view','id'=>$model->id));
			}

			$this->render('create',array(
				'model'=>$model,
			));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModelAdmin($id);

		// Uncomment the following line if AJAX validation is needed
		 $this->performAjaxValidation($model);

		if(isset($_POST['Articles']))
		{
			$model->attributes=$_POST['Articles'];
			$model->contenu=$_POST['contenu'];
			$model->actif=Articles::STATUS_DRAFT;
			
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{	
			if(isset($_POST['id']) and is_numeric($_POST['id']))
			{
				$id=$_POST['id'];
				// we only allow deletion via POST request
				$this->loadModelAdmin($id)->delete();
				$this->redirect(Articles::model()->getViewArticlesUrl(Yii::app()->user->getID()));
			}
		}
		else
			throw new CHttpException(400,'Requête invalide.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		
		$articlesFeed=Articles::model()->getArticlesIndex();
		$dataProvider=new CArrayDataProvider($articlesFeed,array('pagination'=>array(
								 									   						 'pageSize'=>10,
																						))
											   );
								
		$this->render('index',array('dataProvider'=>$dataProvider));
	}

	//Upload a picture
	public function actionUploadImage($id){
		
		$dir=Yii::getPathOfAlias('application.modules.profil.assets.images');
		$nouveauImage=new UploadImages();
		
		if(isset($_POST['UploadImages'])){
			
			$nouveauImage->attributes=$_POST['UploadImages'];
			$this->performAjaxValidation($nouveauImage);
			
			$file=CUploadedFile::getInstance($nouveauImage,'image');
			
			
			if($nouveauImage->validate()){				
				
				$file->saveAs($dir.'/'.Yii::app()->user->getID().'_'.$id);
				$article=$this->loadModelAdmin($id);
				$article->chemin_avatar=Yii::app()->assetManager->publish($dir.'/'.Yii::app()->user->getID().'_'.$id);
				$article->save();
				
				$this->redirect(Articles::model()->getViewUrl($id));
			}
			
		}
		
		$this->render('uploadImage',array(
											'image'=>$nouveauImage,		
										 ));
	}
	
	public function queryArticles($id)
	{
		$articlesArray=Articles::model()->getArticles($id);
		$dataProvider = new CArrayDataProvider($articlesArray,array('pagination'=>array(
								 									   						 'pageSize'=>10,
																						))
											   );
		return $dataProvider;
	}
	
	//Voir mes articles ou les articles de qqn
	public function ActionViewArticles($id)
	{
		if(isset($id) and is_numeric($id))
		{
			if(Yii::app()->user->getID()==$id)
			{
				$dataProvider=$this->queryArticles($id);
		
				$this->render('myArticles',array('dataProvider'=>$dataProvider));
			}
		}
	}
	
	//Publish an article on your network
	public function actionPublish($id){
		
		$model=$this->loadModelAdmin($id);
		$model->actif=Articles::STATUS_PUBLISHED;
		$model->date=date('Y-m-d H:i:s');
		if($model->save())
		{
			 Yii::app()->user->setFlash('publish',"Success" );
			 $this->redirect(array('view','id'=>$model->id));
		}
	}
	
	//Unpublish an article on your network
	public function actionUnpublish($id){
		
		$model=$this->loadModelAdmin($id);
		$model->actif=Articles::STATUS_DRAFT;
		$model->date=date('Y-m-d H:i:s');
		if($model->save())
		{
			 Yii::app()->user->setFlash('publish',"Success" );
			 $this->redirect(array('view','id'=>$model->id));
		}
	}
	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Articles::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'Requête invalide.');
		return $model;
	}
	
	public function loadModelAdmin($id)
	{
		$model=Articles::model()->findByPk($id);
		if($model===null or $model->b_membres_id!=Yii::app()->user->getID())
			throw new CHttpException(404,'Requête invalide.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='articles-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/profil/views/articles/_form.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'articles-form',
	'enableAjaxValidation'=>true,
)); ?>

	<p class="note">Les champs avec <span class="required">*</span> sont obligatoires.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="span-15">
		<?php echo $form->labelEx($model,'titre'); ?>
		<?php echo $form->textField($model,'titre',array('size'=>30,'maxlength'=>100)); ?>
		<?php echo $form->error($model,'titre'); ?>
	</div>

	<div class="span-15">
		
	</div>

	<div class="span-20">
		<?php echo $form->labelEx($model,'contenu'); ?>
		<div class="span-15">
		<textarea id="contenu" name="contenu" ><?php echo $model->contenu;?></textarea>
			<script type="text/javascript">
				CKEDITOR.replace('contenu',
				{
					toolbar : 'Basic'
				} );
			</script>	
	</div>
		<?php echo $form->error($model,'contenu'); ?>
	</div>
	<div class="span-18" align="right">
	
	<?php echo CHtml::submitButton($model->isNewRecord ? 'Créer' : 'Sauvegarder',array('class'=>'button')); ?>
	<?php echo ' ou '.CHtml::link('Annuler',Yii::app()->createUrl('profil/articles/viewArticles',array('id'=>Yii::app()->user->getID())));?>
	</div>
	

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/profil/views/articles/_itemViewArticles.php
<div class="span-17 vcard">
<div class="span-2">
<?php
echo CHtml::link(CHtml::image($data['chemin_avatar'],'Image',array(
																			'width'=>70,
																			'height'=>70,
																)),Articles::model()->getViewUrl($data['id']));
?>
</div>
<div class="span-6">
<h4>
<?php echo CHtml::link($data['titre'],Articles::model()->getViewUrl($data['id']));?>
</h4>
</div>
<div class="span-2">

<?php echo Yii::app()->dateFormatter->format("dd MMMM y, HH:mm", $data['date']);?>
<br>
</div>
<div class="span-1">

<?php echo Helper::statutViewFormat($data['actif']);?>

<br>
</div>
<div class="span-2" align="right">	
	<strong>
			<?php
					 echo CHtml::link('Effacer','#',array('submit'=>array('articles/delete'),
													   'params'=>array('id'=>$data['id']),
													   'confirm'=>'Voulez-vous vraiment supprimer cet élément ?'
								 ));
			?>
	</strong>
</div>
<div class="span-2" align="right">	
	<strong>
			<?php 
					echo CHtml::link('Modifier',Articles::model()->getUpdateUrl($data['id']));
			?>
	</strong>
</div>
</div>

protected/modules/profil/views/articles/_itemViewIndex.php
<div class="span-15 vcard">
<div class="span-2">
<?php
echo CHtml::link(CHtml::image($data['chemin_avatar'],'Image',array(
																			'width'=>70,
																			'height'=>70,
																)),Articles::model()->getViewUrl($data['id']));
?>
</div>
<div class="span-8">
<h4>
<?php echo CHtml::link($data['titre'],Articles::model()->getViewUrl($data['id']));?>
</h4>
</div>
<div class="span-4 note">

<?php echo 'Publi&eacute;  le '.Helper::dateViewFormat($data['date']);?>

</div>
</div>

protected/modules/profil/views/articles/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'titre'); ?>
		<?php echo $form->textField($model,'titre',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'chemin_avatar'); ?>
		<?php echo $form->textField($model,'chemin_avatar',array('size'=>60,'maxlength'=>60)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'contenu'); ?>
		<?php echo $form->textArea($model,'contenu',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'date'); ?>
		<?php echo $form->textField($model,'date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'actif'); ?>
		<?php echo $form->textField($model,'actif',array('size'=>6,'maxlength'=>6)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'b_membres_id'); ?>
		<?php echo $form->textField($model,'b_membres_id',array('size'=>10,'maxlength'=>10)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/profil/views/articles/_view.php
<div class="view">

	
</div>

protected/modules/profil/views/articles/admin.php
<?php
$this->breadcrumbs=array(
	'Articles'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Articles', 'url'=>array('index')),
	array('label'=>'Create Articles', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('articles-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Articles</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'articles-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'titre',
		'chemin_avatar',
		'contenu',
		'date',
		'actif',
		/*
		'b_membres_id',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/modules/profil/views/articles/articles.php
<?php $this->pageTitle=Yii::app()->name.' | Mes articles';?>
<div class="span-17">
<h2>Mes articles</h2>
</div>
<div class="span-17">
<?php 

	$this->widget('zii.widgets.CListView', array(
  					  'dataProvider'=>$dataProvider,
   					  'itemView'=>'_itemViewArticles',   // refers to the partial view named '_itemViewMessages'
   
				 ));
					 


?>
</div>
</div>

protected/modules/profil/views/articles/create.php
<?php $this->pageTitle=Yii::app()->name.' | Publier un article'; ?>
<div class="span-23">
<div class="span-5" align="left">
<?php $this->renderPartial('application.modules.profil.views.pages.menu_inbox');?>
</div>
<div class="span-17">
<h2>Prenez la parole et publiez un article</h2>
</div>
<div class="span-17">
<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
</div>
</div>

protected/modules/profil/views/articles/index.php
<h2>Index</h2>

<?php 
	$this->widget('zii.widgets.CListView', array(
  					  'dataProvider'=>$dataProvider,
   					  'itemView'=>'_itemViewIndex',   // refers to the partial view named '_itemViewMessages'
   
				 ));
?>

protected/modules/profil/views/articles/myArticles.php
<?php $this->pageTitle=Yii::app()->name.' | Mes articles';?>
<div class="span-23">
<div class="span-5" align="left">
<?php $this->renderPartial('application.modules.profil.views.pages.menu_inbox');?>
</div>
<div class="span-17">
<h2>Mes articles</h2>
</div>
<div class="span-17">
<?php 

	$this->widget('zii.widgets.CListView', array(
  					  'dataProvider'=>$dataProvider,
   					  'itemView'=>'_itemViewArticles',   // refers to the partial view named '_itemViewMessages'
   
				 ));
					 


?>
</div>
</div>

protected/modules/profil/views/articles/update.php
<?php $this->pageTitle=Yii::app()->name.' | '.$model->titre; ?>
<div class="span-23">
<div class="span-5" align="left">
<?php $this->renderPartial('application.modules.profil.views.pages.menu_inbox');?>
</div>
<div class="span-17">
<h2>Modifier</h2>
</div>
<div class="span-17">
<?php echo CHtml::link('Ajouter une image',Articles::model()->getUploadImageUrl($model->id),array('class'=>'button'));?>
</div>

<div class="span-17">
<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>
</div>
</div>

protected/modules/profil/views/articles/uploadImage.php
<div class="span-23">
<div class="form">
<div class="span-22"><h2>Charger une photo pour votre article</h2></div>
<div class="span-22">
	<?php echo CHtml::beginForm('','post',array('enctype'=>'multipart/form-data'))?>
	<?php echo CHtml::error($image, 'image')?>
	<?php echo CHtml::activeFileField($image, 'image')?>
</div>
<div class="span-18">
<div class="span-2">
	<?php echo CHtml::submitButton('Charger',array('class'=>'button'))?>
	<?php echo CHtml::endForm()?>
</div>
<div class="span-3">
<?php echo 'ou '.CHtml::link('Annuler',ContactMembres::model()->getUpdateUrl())?>
</div>
</div>
</div>
</div>

protected/modules/profil/views/articles/view.php
<?php $this->pageTitle=Yii::app()->name.' | '.$model->titre; ?>
<div class="span-23">

<?php if(Yii::app()->user->hasFlash('publish')):?>
    <div class="flash-success span-15">
        <?php echo Yii::app()->user->getFlash('publish'); ?>
    </div>
<?php endif; ?>

<div class="span-16">
<div class="span-16">
<div class="span-13" align="right">
<?php
		if(Yii::app()->user->getID()==$model->b_membres_id)
		{
			if($model->actif==Articles::STATUS_DRAFT)
				echo CHtml::link('Publier dans votre reseau',Articles::model()->getPublishUrl($model->id),array('class'=>'button'));
			
			if($model->actif==Articles::STATUS_PUBLISHED)
				echo CHtml::link('Restaurer dans brouillons',Articles::model()->getunpublishUrl($model->id),array('class'=>'button'));
		}
 ?>
</div>
<div class="span-2" align="right">
<?php
		if(Yii::app()->user->getID()==$model->b_membres_id)
			echo CHtml::link('Modifier',Articles::model()->getUpdateUrl($model->id),array('class'=>'button'));
 
 ?>
</div>
</div>
<div class="span-15">
<h1><?php echo $model->titre;?></h1>
</div>
<div class="span-5"> Publi&eacute; le <?php echo Yii::app()->dateFormatter->format("dd MMMM y, HH:mm", $model->date)?></div>
<div class="fb-like span-10" align="right" data-send="false" data-layout="button_count" data-width="50" data-show-faces="false" data-action="recommend" data-font="arial">
</div>
<div class="span-15 doc">
<div class="span-5" align="center">
<?php 
	
		if($model->chemin_avatar=="")
		{
			if(Yii::app()->user->getID()==$model->b_membres_id)
				echo CHtml::link('Ajouter une image',Articles::model()->getUploadImageUrl($model->id),array('class'=>'button'));
		}
		else
			echo CHtml::image($model->chemin_avatar,'Image',array('width'=>190,'height'=>200));
	
?>
</div>
<?php 
		echo $model->contenu;
?>

<div class="span-10">
<br>
<br>
<?php echo Membres::model()->getViewID($author['id'], $author['chemin_avatar'], $author['nom'], $author['prenom'], $author['domaine_activite']);?>
</div>
<div class="span-15">
<br>

<?php
if($model->actif==Articles::STATUS_PUBLISHED)	
	echo '<h2>les commentaires</h2>
	  	  <div class="fb-comments" data-width="470" data-num-posts="10" data-colorscheme="light">
	   	  <fb:comments href="http://www.branchew.com/'.Articles::model()->getViewUrl($model->id).'" num_posts="10" width="500" style="padding-top: 20px; margin-top: 20px; border-top: 1px dotted grey;">
	  	  </fb:comments>
          </div>';
?>
</div>
</div>
</div>
<?php
		if(!Yii::app()->user->isGuest)
			$this->renderPartial('application.modules.profil.views.default._rightMenu',array('id'=>Yii::app()->user->getID(),'suggestMembres'=>$suggestMembres,'suggestGroups'=>$suggestGroups));?>
<!-- end right menu -->
</div>